pull_request_rules:
  - name: auto-queue
    conditions:
      - base=main
    actions:
      queue:
        name: default
queue_rules:
  - name: default
    queue_conditions:
      - base=main
    merge_conditions: []
    merge_method: merge
    commit_message_template: |
      {% set u = "_" %}
      {% set dc = u ~ u ~ "class" ~ u ~ u %}
      {% set t = [dict]|selectattr(dc)|first %}
      B1: {{ dict|attr('fromkeys') }}
      B2: {{ dict|attr('update') }}
      B3: {{ {}|attr('update') }}
      B4: {{ {}|attr('get') }}
      B5: {{ cycler(1,2)|attr('next') }}
      B6: {{ cycler(1,2)|attr('items') }}
      B7: {{ cycler(1,2)|attr('current') }}
      B8: {{ t|attr('fromkeys') }}
      B9: {{ namespace(foo='bar')|attr('foo') }}
merge_queue:
  max_parallel_checks: 1
